config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  resources :tasks do
    resources :task_comments

    put '/follow', to: 'tasks#follow', :as => 'follow'
  end

  get 'dashboard/index'

  resources :projects

  get 'projects/:id/teams', to: 'projects#teams', :as => 'project_teams'
  post 'projects/switch', to: 'projects#switch', :as => 'project_switch'
  post 'projects/:id/teams/:team_id/role', to: 'projects#change_role', :as => 'project_role'
  delete 'projects/:id/teams/:team_id/remove', to: 'projects#remove_team', :as => 'project_team'

  resources :teams
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  get 'account/password', to: 'users#change_password', :as => 'change_password'
  post 'account/password', to: 'users#update_password', :as => 'update_password'

  root to: "dashboard#index"
end

app/models/concerns/tasks/description.rb
module Tasks
  module Description
    extend ActiveSupport::Concern

    def description
      if self[:description].blank?
        return "Empty description"        
      else
        return self[:description]
      end
    end
  end
end

app/models/concerns/tasks/priority.rb
module Tasks
  module Priority
    extend ActiveSupport::Concern

    def priorities
      return ["Uncategorized", "Lowest", "Low", "Normal", "High", "Highest"]
    end

    def priority_label
      return priorities[self.priority]
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include Tasks::Priority
  include Tasks::Description
  acts_as_followable
  
  belongs_to :project
  belongs_to :milestone
  
  has_many :task_comments
  has_many :task_metas

  belongs_to :assigner, :class_name => 'User'
  belongs_to :assignee, :class_name => 'User'

  has_many :task_assets, :dependent => :destroy

  def get_comment_count(count)
    if(!count)
      0
    else
      count
    end
  end
end

app/controllers/concerns/tasks/followable.rb
module Tasks
	module Followable
		extend ActiveSupport::Concern
	
		def follow
			user = current_user
			task = Task.find(params[:task_id])

			respond_to do |format|
				if user.follow(task)
					format.html { redirect_to task, notice: 'Followed task' }
	      			format.json { head :no_content }
				else
					format.html { redirect_to task, notice: 'Not Followed task' }
	      			format.json { head :no_content }
				end
			end
		end
		
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include Tasks::Followable
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.includes(:assigner, :assignee).where(:project_id => session[:project_id]).order(priority: :desc, due: :asc)
    # get the count from the comments efficently
    @task_comment_count = TaskComment.all.includes(@tasks).group(:task_id).count
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comments = Task.find(params[:id]).task_comments.includes(:user)
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @project = Project.find(task_params[:project_id])
    @task = @project.tasks.new(task_params)
    @task.priority = 3
    @task.assigner = current_user
     
    if params[:task][:assets]
      #abort params[:task][:assets].inspect
      #===== The magic is here ;)
      params[:task][:assets].each { |file|
        @task.task_assets.build(user_id: current_user.id, :file => file)
      }
    end

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :assigner_id, :assignee_id, :name, :due, :priority, :description, :task_assets)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_followable.html.erb
<% if current_user.follow?(@task) %>
	<%= link_to '<span class="typcn typcn-eye"></span> Following'.html_safe, task_follow_path(@task), :method => 'put', :remote => true, :class => "btn btn-sm btn-following" %>
<% else %>
	<%= link_to '<span class="typcn typcn-eye-outline"></span> Follow'.html_safe, task_follow_path(@task), :method => 'put', :remote => true, :class => "btn btn-sm btn-follow" %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= f.label :project %>
    <%= f.select :project_id, options_for_select(Project.all.collect {|p| [ p.name, p.id ] }, session[:project_id]), {}, {:class => "form-control"} %>
  </div>

  <div class="field form-group">
    <%= f.label :assignee %>
    <%= f.select :assignee_id, User.all.collect {|p| [ p.name, p.id ] }, {}, {:class => "form-control"} %>
  </div>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :due %>
    <%= f.datetime_select :due, :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: "10", :class => "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :assets %> <br>
    <%= f.file_field :assets, multiple: true %>
  </div>

  <div class="actions form-group">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">

  <!-- left column -->
  <div class="col col-md-8" id="main-content">

    <div class="row">
      <div class="col">
        <table class="table table-sm table-striped table-hover tasks">
          <thead>
            <tr>
              <th>Name</th>
              <th>Assigner</th>
              <th>Assignee</th>
              <th>Due</th>
              <th>Priority</th>
              <th>Comments</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @tasks.each do |task| %>
              <tr class="priority <%= task.priority_label.downcase %>">
                <td><span style="overflow: hidden"><%= link_to task.name, task_path(task), data: { no_turbolink: false } %></span></td>
                <td><%= task.assigner.name %></td>
                <td><%= task.assignee.name %></td>
                <td><%= task.due %></td>
                <td><%= task.priority_label %></td>
                <td><%= get_count(@task_comment_count[task.id]) %></td>
                <td><%= link_to 'Show', task %></td>
                <td><%= link_to 'Edit', edit_task_path(task) %></td>
                <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


    <%= link_to 'New Task', new_task_path, :class => "btn btn-success" %>

  </div>
  <!-- end: left col -->

  <div class="col col-md-4" id="sidebar">
  </div>

</div>  

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<% title @task.name %>

<div class="row">

  <!-- left column -->
  <div class="col col-md-8" id="main-content">

  	<!-- begin task header -->
	<div class="row">
	  <div class="col">
		<h2><%= @task.name %></h2>
	  </div>
	</div>

	<div class="row">
	  <div class="col col-md-10">
		<strong>Due: </strong> <%= @task.due %> <br>
		<strong>Assignee: </strong> <%= link_to @task.assignee.name, user_path(@task.assignee) %> <br>
		<span class="badge priority-<%= @task.priority_label.downcase %> text-uppercase"><%= @task.priority_label %></span>
	  </div>
	  <div class="col col-md-2 text-right">
		<%= render 'tasks/followable' %>
	  </div>
	</div>
	<!-- end task header -->

	<div class="row">
		<div class="col">
		  	<div id="task-description">
				<%= markdown(@task.description) %>
		  	</div>
		</div>
	</div>

  </div>
  <!-- end: left col -->

  <div class="col col-md-4" id="sidebar">
  	<!-- begin comments row -->
  	<div class="row">
  		<div class="col">
		  	<div id="task-comments">
			    <% @comments.each do |comment| %>
			    <div class="media comment">
				  <div class="media-body comment-body">
				    <h6 class="mt-0 mb-1"><%= comment.user.name %> <span class="comment-datetime">posted <%= time_ago_in_words(comment.created_at) %> ago</span></h6>
					<%= markdown(comment.comment) %>
				  </div>
				</div>
			    <% end %>
			    <div class="media comment">
				  <div class="media-body comment-body">
					<%= form_for([@task, @task.task_comments.build], remote: true) do |f| %>
					  <% if @task.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task_comment from being saved:</h2>

					      <ul>
					      <% @task.errors.full_messages.each do |message| %>
					        <li><%= message %></li>
					      <% end %>
					      </ul>
					    </div>
					  <% end %>

				      <div class="form-group">
					    <%= f.label :comment, "Enter your comment" %>
					    <%= f.text_area(:comment, :class => "form-control", :rows => 5) %>
					  </div>

					  <div class="actions form-group">
					    <%= f.submit "Submit", :class => "btn btn-sm btn-success" %>
					  </div>
					<% end %>
				  </div>
				</div>
		  	</div>
  		</div>
  	</div>
  	<!-- end comments row -->
  </div>
</div>