config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  resources :tasks do
    resources :task_comments

    put '/follow', to: 'tasks#follow', :as => 'follow'
  end

  get 'dashboard/index'

  resources :projects

  get 'projects/:id/teams', to: 'projects#teams', :as => 'project_teams'
  post 'projects/switch', to: 'projects#switch', :as => 'project_switch'
  post 'projects/:id/teams/:team_id/role', to: 'projects#change_role', :as => 'project_role'
  delete 'projects/:id/teams/:team_id/remove', to: 'projects#remove_team', :as => 'project_team'

  resources :teams
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  get 'account/password', to: 'users#change_password', :as => 'change_password'
  post 'account/password', to: 'users#update_password', :as => 'update_password'

  root to: "dashboard#index"
end

app/models/task_comment.rb
class TaskComment < ApplicationRecord
  include PublicActivity::Model
  tracked owner: proc {|controller, model_instance| controller.current_user }, recipient: :task, :params => {
      :user_id => proc {|controller, model_instance| controller.current_user.id },
      :user_name => proc {|controller, model_instance| controller.current_user.name },
      :task_id => proc {|controller, model_instance| model_instance.task.id},
      :task_name => proc {|controller, model_instance| model_instance.task.name},
      :comment => :comment
  }

  belongs_to :user
  belongs_to :task, counter_cache: true

  # Validation
  validates :comment, presence: true, length: { minimum: 2 }
end

app/controllers/task_comments_controller.rb
class TaskCommentsController < ApplicationController
  before_action :set_task_comment, only: [:show, :edit, :update, :destroy]

  # GET /task_comments
  # GET /task_comments.json
  def index
    @task_comments = TaskComment.all
  end

  # GET /task_comments/1
  # GET /task_comments/1.json
  def show
  end

  # GET /task_comments/new
  def new
    @task_comment = TaskComment.new
  end

  # GET /task_comments/1/edit
  def edit
  end

  # POST /task_comments
  # POST /task_comments.json
  def create
    @task = Task.find(params[:task_id])
    @task_comment = @task.task_comments.new(task_comment_params)
    @task_comment.user = current_user

    respond_to do |format|
      if @task_comment.save
        format.html { redirect_to @task, notice: 'Task comment was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { redirect_to @task }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_comments/1
  # PATCH/PUT /task_comments/1.json
  def update
    respond_to do |format|
      if @task_comment.update(task_comment_params)
        format.html { redirect_to @task_comment, notice: 'Task comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_comment }
      else
        format.html { render :edit }
        format.json { render json: @task_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_comments/1
  # DELETE /task_comments/1.json
  def destroy
    @task_comment.destroy
    respond_to do |format|
      format.html { redirect_to task_comments_url, notice: 'Task comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_comment
      @task_comment = TaskComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_comment_params
      params.require(:task_comment).permit(:user_id, :task_id, :comment)
    end
end

app/helpers/task_comments_helper.rb
module TaskCommentsHelper
end

app/views/task_comments/_form.html.erb
<%= form_for(task_comment) do |f| %>
  <% if task_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_comment.errors.count, "error") %> prohibited this task_comment from being saved:</h2>

      <ul>
      <% task_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :task_id %>
    <%= f.text_field :task_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_comments/edit.html.erb
<h1>Editing Task Comment</h1>

<%= render 'form', task_comment: @task_comment %>

<%= link_to 'Show', @task_comment %> |
<%= link_to 'Back', task_comments_path %>

app/views/task_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Task</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_comments.each do |task_comment| %>
      <tr>
        <td><%= task_comment.user %></td>
        <td><%= task_comment.task %></td>
        <td><%= task_comment.comment %></td>
        <td><%= link_to 'Show', task_comment %></td>
        <td><%= link_to 'Edit', edit_task_comment_path(task_comment) %></td>
        <td><%= link_to 'Destroy', task_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Comment', new_task_comment_path %>

app/views/task_comments/new.html.erb
<h1>New Task Comment</h1>

<%= render 'form', task_comment: @task_comment %>

<%= link_to 'Back', task_comments_path %>

app/views/task_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task_comment.user %>
</p>

<p>
  <strong>Task:</strong>
  <%= @task_comment.task %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @task_comment.comment %>
</p>

<%= link_to 'Edit', edit_task_comment_path(@task_comment) %> |
<%= link_to 'Back', task_comments_path %>