config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  resources :tasks do
    resources :task_comments

    put '/follow', to: 'tasks#follow', :as => 'follow'
  end

  get 'dashboard/index'

  resources :projects

  get 'projects/:id/teams', to: 'projects#teams', :as => 'project_teams'
  post 'projects/switch', to: 'projects#switch', :as => 'project_switch'
  post 'projects/:id/teams/:team_id/role', to: 'projects#change_role', :as => 'project_role'
  delete 'projects/:id/teams/:team_id/remove', to: 'projects#remove_team', :as => 'project_team'

  resources :teams
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  get 'account/password', to: 'users#change_password', :as => 'change_password'
  post 'account/password', to: 'users#update_password', :as => 'update_password'

  root to: "dashboard#index"
end

app/models/concerns/projects/status.rb
module Projects
  module Status
    extend ActiveSupport::Concern

    def statuses
      return ["Closed", "Open", "Archived"]
    end

    def status_label
      return statuses[self[:status]]
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  include Projects::Status
  include PublicActivity::Model
  tracked
  acts_as_followable

  has_many :project_users
  has_many :project_teams
  has_many :users, :through => :project_users
  has_many :teams, :through => :project_teams

  has_many :tasks


  # Validation
  validates :name, uniqueness: true, presence: true
end

app/controllers/concerns/projects/teams.rb
module Projects
  module Teams
    extend ActiveSupport::Concern

    def teams
      @teams = Project.find(params[:id]).teams

      # get the count from the teams efficently
      @team_members_count = TeamMember.all.includes(@teams).group(:team_id).count
    end

    def change_role
      @project = Project.find(params[:id])
      
      project_team = @project.project_teams.where(team_id: params[:team_id])
      project_team.update(:team_id=> params[:team_id], :role_id=> params[:role_id])
       
      respond_to do |format|
          format.html { redirect_to project_teams_url(@project.id), notice: 'Role changed.' }
          format.json { head :no_content }
      end
      
    end

    def remove_team
      
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Projects::Teams

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    # get the count from the tasks efficently
    @project_tasks_count = Task.all.includes(@projects).group(:project_id).count
    @project_teams_count = ProjectTeam.all.includes(@projects).group(:project_id).count
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks = Project.find(params[:id]).tasks.includes(:assigner, :assignee).order(priority: :desc, due: :asc)

    # get the count from the comments efficently
    @task_comment_count = TaskComment.all.includes(@tasks).group(:task_id).count
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    # status open by default
    @project.status = 1

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def switch
    session[:project_id] = params[:project_id]
    current_user.personal_settings.first_or_create(setting_key: "current_project", setting_value: session[:project_id]).update(setting_value: session[:project_id])
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Switched project.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :status, :team_id, :role_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <% if action_name != "new" %>
    <div class="field form-group">
      <%= f.label :status %>
      <%= f.text_field :status, :class => "form-control" %>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="row">

  <!-- left column -->
  <div class="col col-md-8" id="main-content">

    <h1>Projects</h1>

    <table class="table table-sm table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Tasks</th>
          <th>Status</th>
          <th>Teams</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><strong><%= link_to project.name, project_path(project) %></strong></td>
            <td><%= get_count(@project_tasks_count[project.id]) %></td>
            <td><%= project.status_label %></td>
            <td><%= get_count(@project_teams_count[project.id]) %></td>
            <td><%= link_to 'Show', project %></td>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Project', new_project_path %>

  </div>
  <!-- end: left col -->

  <div class="col col-md-4" id="sidebar">
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-12">
  	<h1>New Project</h1>

	<%= render 'form', project: @project %>

	<%= link_to 'Back', projects_path %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">

  <!-- left column -->
  <div class="col col-md-8" id="main-content">
  
    <div class="row">
      <div class="col">
        <%= link_to '&laquo;'.html_safe + ' Go Back', projects_path %>
      </div>
    </div>

    <hr>

    <div class="row">
      <div class="col">
        <h5 class="editable"><%= @project.name %></h5>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <strong>Status:</strong> <%= @project.status %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <table class="table table-sm table-striped table-hover table-bordered tasks">
          <thead>
            <tr>
              <th>Name</th>
              <th>Assigner</th>
              <th>Assignee</th>
              <th>Due</th>
              <th>Priority</th>
              <th>Comments</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @tasks.each do |task| %>
              <tr class="priority <%= task.priority_label.downcase %>">
                <td><%= link_to task.name, task_path(task) %></td>
                <td><%= task.assigner.name %></td>
                <td><%= task.assignee.name %></td>
                <td><%= task.due %></td>
                <td><%= task.priority_label %></td>
                <td><%= get_count(@task_comment_count[task.id]) %></td>
                <td><%= link_to 'Show', task %></td>
                <td><%= link_to 'Edit', edit_task_path(task) %></td>
                <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>


  </div>
  <!-- end: left col -->

  <div class="col col-md-4" id="sidebar">
  </div>
</div>

app/views/projects/teams.html.erb
<h1>Teams</h1>

<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th>Team</th>
      <th>Members</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><strong><%= link_to team.name, team_path(team) %></strong></td>
        <td><%= get_count(@team_members_count[team.id]) %></td>
        <td>
			<%= form_tag(project_role_path(params[:id], team.id), :id => "filter_form", :method => "post", :remote => true) do |f| %>
			  <%= select_tag(:role_id, options_from_collection_for_select(Role.all.order(power: :desc), :id, :name, team.roles.ids), class: 'form-control form-control-sm project_team_role selective') %>
			<% end %>
        </td>
        <td><%= link_to 'Remove', project_team_path(params[:id], team.id) %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team', new_team_path %>