config/routes.rb
Rails.application.routes.draw do
  resources :milestones
  resources :tasks do
    resources :task_comments

    put '/follow', to: 'tasks#follow', :as => 'follow'
  end

  get 'dashboard/index'

  resources :projects

  get 'projects/:id/teams', to: 'projects#teams', :as => 'project_teams'
  post 'projects/switch', to: 'projects#switch', :as => 'project_switch'
  post 'projects/:id/teams/:team_id/role', to: 'projects#change_role', :as => 'project_role'
  delete 'projects/:id/teams/:team_id/remove', to: 'projects#remove_team', :as => 'project_team'

  resources :teams
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  get 'account/password', to: 'users#change_password', :as => 'change_password'
  post 'account/password', to: 'users#update_password', :as => 'update_password'

  root to: "dashboard#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  # extend ActsAsFollower::FollowerLib
  # extend ActsAsFollower::FollowScopes

  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/milestone.rb
class Milestone < ApplicationRecord
  belongs_to :project
  has_many :tasks
end

app/models/personal_setting.rb
class PersonalSetting < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  include Projects::Status
  include PublicActivity::Model
  tracked
  acts_as_followable

  has_many :project_users
  has_many :project_teams
  has_many :users, :through => :project_users
  has_many :teams, :through => :project_teams

  has_many :tasks


  # Validation
  validates :name, uniqueness: true, presence: true
end

app/models/project_team.rb
class ProjectTeam < ApplicationRecord
  belongs_to :project
  belongs_to :team
  belongs_to :role
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :teams, :through => :project_teams
  has_many :projects, :through => :project_teams
  
  # Check if user is authorized by minimum role
  # Using the power value to determine if user has sufficent privileges
  def is_authorized(min_role)
    @roles = Role.all.group(:name)

    authorized = false
    if @roles[self[:name]] >= @roles[min_role]
      authorized = true
    end

    return authorized
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include Tasks::Priority
  include Tasks::Description
  acts_as_followable
  
  belongs_to :project
  belongs_to :milestone
  
  has_many :task_comments
  has_many :task_metas

  belongs_to :assigner, :class_name => 'User'
  belongs_to :assignee, :class_name => 'User'

  has_many :task_assets, :dependent => :destroy

  def get_comment_count(count)
    if(!count)
      0
    else
      count
    end
  end
end

app/models/task_asset.rb
class TaskAsset < ApplicationRecord
  belongs_to :task
  belongs_to :user

  # Paperclip
  has_attached_file :file,
    :styles => {
      :thumb=> "100x100#",
      :small  => "150x150>",
      :medium => "300x300>",
      :large =>   "400x400>" }
  validates_attachment :file, content_type: { content_type: ["image/jpg", "image/jpeg",     "image/png", "image/gif"] }

  attr_accessor :file_file_name
end

app/models/task_comment.rb
class TaskComment < ApplicationRecord
  include PublicActivity::Model
  tracked owner: proc {|controller, model_instance| controller.current_user }, recipient: :task, :params => {
      :user_id => proc {|controller, model_instance| controller.current_user.id },
      :user_name => proc {|controller, model_instance| controller.current_user.name },
      :task_id => proc {|controller, model_instance| model_instance.task.id},
      :task_name => proc {|controller, model_instance| model_instance.task.name},
      :comment => :comment
  }

  belongs_to :user
  belongs_to :task, counter_cache: true

  # Validation
  validates :comment, presence: true, length: { minimum: 2 }
end

app/models/task_meta.rb
class TaskMeta < ApplicationRecord
  belongs_to :project
end

app/models/task_meta_data.rb
class TaskMetaData < ApplicationRecord
  belongs_to :task_meta
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_members
  has_many :project_teams

  has_many :users, :through => :team_members
  has_many :projects, :through => :project_teams

  has_many :roles, :through => :project_teams
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_follower
  has_many :team_members
  has_many :teams, :through => :team_members

  has_many :project_users
  has_many :projects, :through => :project_users

  has_many :owned_tasks, :class_name => 'Task', :foreign_key => 'assigner_id'
  has_many :assigned_tasks, :class_name => 'Task', :foreign_key => 'assignee_id'

  has_many :task_comments

  has_one :role, :through => :project_teams

  has_many :task_assets, :dependent => :destroy

  has_many :personal_settings, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.erb
<% if alert %>
	<div class="alert alert-warning alert-dismissible top-notification" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_notice.html.erb
<% if notice %>
	<div class="alert alert-info alert-dismissible top-notification" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		<%= notice %>
	</div>
<% end %>

app/views/layouts/_sidenav.html.erb
<nav class="navbar navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li>
                        <%= link_to('<span class="typcn typcn-home-outline"></span> Dashboard'.html_safe, dashboard_index_path, :class => "nav-link")  %>
                    </li>
                    <li>
                        <%= link_to('<span class="typcn typcn-book"></span> Projects'.html_safe, projects_path, :class => "nav-link")  %>
                        <ul class="nav nav-second-level collapse">
                            <li><a href="">New Project</a></li>
                        </ul>
                    </li>
                    <li>
                        <%= link_to('<span class="typcn typcn-tick-outline"></span> Tasks'.html_safe, tasks_path, :class => "nav-link")  %>
                    </li>
                    <li>
                        <%= link_to('<span class="typcn typcn-group-outline"></span> Teams'.html_safe, teams_path, :class => "nav-link")  %>
                    </li>
                    <li>
                        <%= link_to('<span class="typcn typcn-user-outline"></span> Users'.html_safe, users_path, :class => "nav-link")  %>
                    </li>
                </ul>

            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  <% if yield(:title).present? %>
    <%= yield(:title) %>
  <% else %>
    Lamb Project Management
  <% end %>
  </title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= body_css_class %>">
<%= render "layouts/notice" %>
<%= render "layouts/alert" %>

<% if user_signed_in? %>
<div class="masthead">
    <nav class="navbar navbar-toggleable-md navbar-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">lamb project</a>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= form_tag(project_switch_path, :id => "filter_form", :method => "post", :remote => true) do |f| %>
              <%= select_tag(:project_id, options_from_collection_for_select(Project.all.order(:name), :id, :name, session[:project_id]), class: 'form-control form-control-sm project-switch selective') %>
            <% end %>
          </li>
        </ul>

        <div class="dropdown">
          <button class="btn btn-sm btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </button>
        
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= render 'devise/menu/registration_items' %>
            <%= render 'devise/menu/login_items' %>
          </ul>
        </div>
      </div>
    </nav>
</div>
<% end %>

<%= render 'layouts/sidenav' %>

<div class="container-wrapper container-fluid">

  <%= yield %>

</div><!-- /.container -->

<footer class="footer">
  <p class="text-center">
    <span class=" align-middle">Copyright &copy; 2017 Lamb</span>
  </p>
</footer>

</body>
</html>

app/views/sidebar/_account.html.erb
    <nav class="sidebar-links">
        <div class="sidebar-nav-group">
            <h6>General</h6>
            <ul class="nav sidenav">
                <li class="">
                    <a href="/account/settings">Account Settings</a>
                </li>
                <li class="">
                    <a href="/account/email">Change email address</a>
                </li>
                <li class="">
                    <a href="/account/services">Services</a>
                </li>
            </ul>
        </div>
        <div class="sidebar-nav-group">
            <h6>Security</h6>
            <ul class="nav sidenav">
                <li class="">
                    <a href="/account/password">Change password</a>
                </li>
            </ul>
        </div>
        <div class="sidebar-nav-group">
            <h6>Billing</h6>
            <ul class="nav sidenav">
                <li class="">
                    <a href="/account/billing">Billing details</a>
                </li>
            </ul>
        </div>
    </nav>